### ISSUE TITLE
Add Screenshots!

### ISSUE THREAD

**Issue by colelawrence** [SamBumgardner/Strategy-Game#4]
I would highly recommend adding a couple screenshots of the game to attract attention from potential contributors in the future.

Or a screen recording or whatever you think of!

Just a thought 👍

**Comment by SamBumgardner** [comment]
You are correct!

Right now I'm laying down a lot of groundwork, though, so there isn't much to screenshot that is guaranteed to remain the same for very long. As the project starts to stabilize, though, I will definitely take a few and throw them in the readme.

**Comment by colelawrence** [comment]
Cool! I thought that this was a project you've showed me before. So, I was
thinking that out of the games you've showed me, there are some great
screenshots or asset galleries you could show.

**Comment by SamBumgardner** [comment]
We have a screenshot up now, and will likely add more as the project continues!
Issue was resolved in commit 7625db7.
